### GET All games
GET http://localhost:5165/games

### GET Game by ID
GET http://localhost:5165/games/4

### PUT Update a game
PUT http://localhost:5165/games/4
Content-Type: application/json

{
    "id": 4,
    "title": "Mario Kart 8 Deluxe Updated",
    "genreId": 2,
    "price": 29.99,
    "releaseDate": "2020-04-28",
    "developer": "Nintendo",
    "publisher": "Nintendo"
}

### POST Create a new game
POST http://localhost:5165/games
Content-Type: application/json

{
    "title": "Mario Kart 8 Deluxe",
    "genreId": 2,
    "price": 19.99,
    "releaseDate": "2020-04-28",
    "developer": "Nintendo",
    "publisher": "Nintendo"
}

### DELETE a game
DELETE http://localhost:5165/games/3
